name: 'Create Release'

on:
  push:
    branches:
      - 'master'
      
# on:
#   push:
#     tags:
#       - 'v*'
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: avakar/tag-and-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
