name: 'Create Release'

# on:
#   push:
#     tags:
#       - "v*"

# on:
#   workflow_run:
#     workflows:
#       - 'Bump Version'
#     types:
#       - completed

# jobs:
#   release:
#     name: "Release"
#     runs-on: "ubuntu-latest"
#     steps:
#       - uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           prerelease: false
#           automatic_release_tag: ${{ $NEW_TAG }} 

on: push
          
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
