name: 'Create Release'

# on:
#   push:
#     tags:
#       - "v*"
on:
  workflow_run:
    workflows:
      - 'Bump Version'
    types:
      - completed

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "$NEW_TAG"
